{% set name = "diptest" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Used GH since pypi version missed test data for upstream tests
  url: https://github.com/RUrlus/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f96ac0f1c0286d6ae9a3a4e25fc00d5dd868cfe33a2218ff0fe2e904091a542f

build:
  skip: True                  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}   # [linux]
    - make                    # [linux]
    - cmake >=3.16
  host:
    - python
    - scikit-build-core >=0.3.3
    - pybind11
    - pip
  run:
    - python
    - psutil
    - numpy >=1.18
    - _openmp_mutex           # [linux]

test:
  imports:
    - diptest
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/RUrlus/diptest
  summary: Hartigan's diptest.
  dev_url: https://github.com/RUrlus/diptest
  doc_url: https://github.com/RUrlus/diptest#readme
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  description: A Python/C(++) implementation of Hartigan & Hartigan's dip test for unimodality.

extra:
  recipe-maintainers:
    - mohamedlarbisentissi
